# Generated by Django 3.0.6 on 2020-06-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('materie', models.CharField(default=' ', max_length=40)),
                ('credite', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('an', models.IntegerField(default=1)),
                ('materie1', models.CharField(default='Geometrie computationala', max_length=40)),
                ('nota1', models.IntegerField(default=0)),
                ('materie2', models.CharField(default='Calculabilitate si complexitate', max_length=40)),
                ('nota2', models.IntegerField(default=0)),
                ('materie3', models.CharField(default='Tehnici web', max_length=40)),
                ('nota3', models.IntegerField(default=0)),
                ('materie4', models.CharField(default='Tehnici avansate de programare', max_length=40)),
                ('nota4', models.IntegerField(default=0)),
                ('materie5', models.CharField(default='Probabilitate si statistica', max_length=40)),
                ('nota5', models.IntegerField(default=0)),
                ('materie6', models.CharField(default='Sisteme de operare', max_length=40)),
                ('nota6', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('medie', models.IntegerField(default=0)),
            ],
        ),
    ]
