# Generated by Django 3.0.6 on 2020-06-12 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materials_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 4, 8, 25, 706175), verbose_name='date published'),
        ),
    ]
